#!/usr/bin/env sh

if [ -z "$BASH_COMPLETION_PREFIX" ]; then
  BASH_COMPLETION_PREFIX=
fi
if [ -f "$BASH_COMPLETION_PREFIX"/etc/bash_completion ]; then
  . "$BASH_COMPLETION_PREFIX"/etc/bash_completion
fi
