#!/usr/bin/env sh
alias be='bundle exec'
alias bespec='bundle exec rspec'

which subl
if [ $? ]
then
  EDITOR=subl
fi

test -z $EDITOR && which vim
if [ $? ]
then
  EDITOR=vim
fi

export BUNDLER_EDITOR=$EDITOR
