#!/usr/bin/env sh

if [ -z "$NVM_PREFIX" ]; then
  NVM_PREFIX="$HOME/.nvm"
fi

NVM_SH="$NVM_PREFIX/nvm.sh"
if [ -f "$NVM_SH" ]; then
  export NVM_DIR="$NVM_PREFIX"
  . "$NVM_SH"
  export PATH=$PATH:$HOME/.node_modules/bin
fi
