#!/usr/bin/env sh

NVM_DIR="$HOME/.nvm"
if [ $(which brew) ]; then
  NVM_SH="$(brew --prefix nvm)/nvm.sh"
else
  NVM_SH="$NVM_DIR/nvm.sh"
fi
echo out
if "$NVM_SH"; then
  export NVM_DIR
  . "$NVM_SH"
  export PATH=$PATH:$HOME/.node_modules/bin
fi
